# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ["GMAIL_USERNAME"] %>
  email_provider_password: <%= ["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ["OWNER_EMAIL"] %>
  secret_key_base: 19cc3bd787ea6a8ceecd473db11401c96b3d6dce40e340d083bfebd44b0f7760fb6b2863763abad723cd052f7e76b4dc7195dfa4599aea13b1b67942cd5322a1

test:
  secret_key_base: 6e530fca72c1c5be39e907bcab4e8c97ba02f4f378daa08fe9398b901b7cb6fdc053f296eb12493d9544da76ed8c304cd1cc87fc2cd96f8a49310dfc11f3917a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ["GMAIL_USERNAME"] %>
  email_provider_password: <%= ["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ["MAILCHIMP_LIST_ID"] %>
  domain_name: <% = ["DOMAIN_NAME"] %>
  owner_email: <%= ["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
